url: https://badbruce.github.io
baseurl: /harvest-demo2/

# Site settings
title: HarvestAPI
email: your-email@domain.com
description: "HarvestAPI Main Page"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/codeforthecaribbean/harvestapi


# Build settings
markdown: kramdown
permalink: pretty